In [ ]:
import numpy as np
x = ([1,2,3],[4,5,6],[7,1,0])
arr = np.array(x)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
arr.sum(axis = 0)

array([12,  8,  9])

In [ ]:
arr.sum(axix=1)

In [ ]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [ ]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [ ]:
arr.flat

In [ ]:
for item in arr.flat:
 print(item)

1
2
3
4
5
6
7
1
0


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
arr.ndim

2

In [ ]:
one = np.array([1,3,4,634,2])
one.argmax()

np.int64(3)

In [ ]:
one.argmin()


np.int64(0)

In [ ]:
arr.argmax(axis=0)

array([2, 1, 1])

In [ ]:
np.where(arr>5)

(array([1, 2]), array([2, 0]))

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5,6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [ ]:
import numpy as np
arr = np.arange(2,21,2)
print(arr)

print(arr[2])
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(arr)
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
matrix = arr.reshape(3,4)
print(matrix)
hole = 5*matrix
print(hole)
trans=matrix.T
print(trans)










[ 2  4  6  8 10 12 14 16 18 20]
6
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
